import { NextResponse } from 'next/server';

export const dynamic = "force-static";


const rowsData = [
  {
    title: "Custom Manifestation Movie",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Daily Positive Affirmations",
    imageSrc: "/images/placeholder.png",
    numberOfVideos: 23,
    videoCount: 43123,
    tagLine: "Start Your Day with Positive Energy",
    likes: 457,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
];

export async function GET() {
   return NextResponse.json(rowsData);
}
