
import type { Metadata } from "next";
import "./globals.css";

import { Poppins, } from "next/font/google";
import ClientProvider from "./ClientProvider";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Brainflow Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
          <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
