import { NextResponse } from "next/server";

export const dynamic = "force-static";


const rowsData = [
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    duration: "13:43",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    category: "Daily Positive Affirmations",
    status: "Free",
    imgSrc: "/images/placeholder.png",
    likes: 457,
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Custom Manifestation Movie",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Premium",
    duration: "13:43",

    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Custom Manifestation Movie",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Free",
    duration: "13:43",

    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Custom Manifestation Movie",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Premium",
    duration: "13:43",

    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    category: "Daily Positive Affirmations",
    status: "Premium",
    duration: "13:43",

    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Custom Manifestation Movie",

    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Premium",
    duration: "13:43",

    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Premium",
    duration: "13:43",

    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Premium",
    likes: 457,
    duration: "13:43",

    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    description: "Lorem ipsum dolor sit amet, consectetur.",

    status: "Premium",
    likes: 457,
    duration: "13:43",

    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    status: "Premium",
    duration: "13:43",

    description: "Lorem ipsum dolor sit amet, consectetur.",
    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },

  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Premium",
    duration: "13:43",

    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    status: "Premium",
    duration: "13:43",

    description: "Lorem ipsum dolor sit amet, consectetur.",
    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    status: "Premium",
    duration: "13:43",

    likes: 457,
    description: "Lorem ipsum dolor sit amet, consectetur.",
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    status: "Premium",
    likes: 457,
    duration: "13:43",

    description: "Lorem ipsum dolor sit amet, consectetur.",
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    status: "Premium",
    duration: "13:43",

    description: "Lorem ipsum dolor sit amet, consectetur.",
    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    status: "Premium",
    duration: "13:43",

    description: "Lorem ipsum dolor sit amet, consectetur.",
    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    status: "Premium",
    duration: "13:43",

    description: "Lorem ipsum dolor sit amet, consectetur.",
    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Free",
    likes: 457,
    duration: "13:43",

    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Free",
    duration: "13:43",

    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Free",
    duration: "13:43",

    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Free",
    duration: "13:43",

    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    uploadDate: "2 April 2024",
    duration: "13:43",

    category: "Daily Positive Affirmations",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Free",
    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
  {
    title: "Mental Training",
    duration: "13:43",

    uploadDate: "2 April 2024",
    category: "Daily Positive Affirmations",
    description: "Lorem ipsum dolor sit amet, consectetur.",
    status: "Free",
    likes: 457,
    imgSrc: "/images/placeholder.png",
    viewCount: 11234,
    saved: 75,
    onView: () => console.log("View clicked"),
    onDelete: () => console.log("Delete clicked"),
  },
];

export async function GET(request: Request) {
  const url = new URL(request.url);

  const category = url.searchParams.get('category')?.split('%').join(' '); 
  if (category) {
    const filteredData = rowsData.filter(row => row.category === category);
    
    return NextResponse.json(filteredData);
  }

  return NextResponse.json(rowsData);
}